### ISSUE TITLE
TEI output: single date values not ISO compliant

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#12]
See entity : https://dev-02.cwrc.ca/islandora/object/cwrc:628a3488-ce4f-440d-a5a9-69ff939ec281/manage/datastreams - birth date

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/3ffe8d7d6f6ab34ea9067e3f6f042f786a839ab9

**Comment by ilovan** [comment]
Can't confirm because #23

**Comment by ilovan** [comment]
Confirmed
