### ISSUE TITLE
xml:lang dropdown and values- how difficult would it be to replace ISO 639-2 with ISO 639-3, which is the more comprehensive

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#14]
JUst asking, @ajmacdonald , I know we specified ISO 639-2 in the mappings.

**Comment by ajmacdonald** [comment]
It would not be difficult.

**Comment by ajmacdonald** [comment]
I'm testing out the language dropdown with the ISO 639-3 values. The source I found ( https://github.com/wooorm/iso-639-3 ) is much more extensive than the previous source I was using ( https://github.com/haliaeetus/iso-639 ): ~7000 entries vs ~500 entries. The dropdown is now extremely slow to interact with. I'm not sure what a good solution is.

**Comment by ilovan** [comment]
The previous source was combining 639-2T and 639-2B, which resulted in some languages appearing twice (both sets contain the same languages, but 639-2B uses the English name of the languages to generate the 3 letter code)

639-3 has better optics due its comprehensiveness:  this is in its Wikipedia entry:

> Because it provides comprehensive language coverage, giving equal opportunity for all languages, and because of its wide adoption in information technologies, ISO 639-3 provides an important technology component addressing the digital divide problem. 

What do you think @SusanBrown . For performance, we're better off using 639-2T which contains 555 language codes, for individual languages and most language families (see https://en.wikipedia.org/wiki/ISO_639-2)

The more inclusive 639-3 contains over 7700 languages, and I can believe Andrew that it would be a drain on the system. 


On the other hand, there is the question of representation.

**Comment by SusanBrown** [comment]
If this would not be a major thing to change down the road, let's go with 639-2T for the time being.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/245204a9a5e7c8270fe8e2a388be15ec9fca8fae

**Comment by ilovan** [comment]
Programmatically would not be difficult, as Andrew mentioned. 
In terms of data consistency, it would not be an issue either, since the codes are consistent across the two specifications (i.e. if a language has a three letter code in 639-2T, it has the same code in 639-3)

**Comment by ilovan** [comment]
Confirmed
