### ISSUE TITLE
TEI output: xml:lang dropdown and values - ISO standard not implemented yet

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#15]
In the language dropdown, there are two entries for some languages (e.g. Slovak, Romanian).
For the two Romanian dropdown entries, two different values are returned (ron and rum)
ron is the language code for  ISO 639-2T and ISO 639-3, while rum is the language code for ISO 639-2B.

If possible, we should go with ISO 639-3 (see #14 )
If not, ISO 639-2T is the way to go.

**Comment by ilovan** [comment]
My guess is that at the moment you are concatenating ISO 639-2T and ISO 639-2B, right, @ajmacdonald ?

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/245204a9a5e7c8270fe8e2a388be15ec9fca8fae

**Comment by ilovan** [comment]
confirmed
