### ISSUE TITLE
Reorganize add/remove field buttons for repeated tags (e.g. name)

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#18]
This is how a fieldset looks like when you have multiple instances of the same tag (e.g. name):
![image](https://user-images.githubusercontent.com/6600070/42947512-b64d62c2-8b2a-11e8-9615-1c93ef7044be.png)

This is what we would want instead:
![2018-07-19 08-26](https://user-images.githubusercontent.com/6600070/42948950-e098ef26-8b2d-11e8-9917-f21258a4c29f.jpg)

**Comment by ajmacdonald** [comment]
You've removed the buttons for adding and removing additional instances of the fieldset...

**Comment by ilovan** [comment]
Nope, that's actually the parent field set. (I just added a label for the individual variant, as it is currently missing in the form (let me know if you want me to set up a separate ticket)

![2018-07-19 09-20](https://user-images.githubusercontent.com/6600070/42954108-22c15568-8b39-11e8-8223-df22ce89c380.jpg)

**Comment by ajmacdonald** [comment]
Ok I understand now. Should there be a remove button in the top right of the Variant name fieldset?

**Comment by SusanBrown** [comment]
I would think so. @ilovan ?

**Comment by ilovan** [comment]
You're right, there should be:

![2018-07-19 09-20](https://user-images.githubusercontent.com/6600070/42956142-77a0fcd4-8b3c-11e8-975a-7883518e3103.jpg)

**Comment by ilovan** [comment]
You're both right, there should be:
![2018-07-19 10-14](https://user-images.githubusercontent.com/6600070/42956273-cb2ded3a-8b3c-11e8-8bdf-8717c1294cf5.jpg)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/37d79208ba56fdc430e0eb12c46dd851d0738e86

**Comment by ilovan** [comment]
confirmed
