### ISSUE TITLE
Add affiliation to the person form

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#2]
This is definitely on me since the mappings and form mockups should have been updated to reflect the most up-to-date feedback received from projects: 
Under properties, add another field called Affiliation, with a certainty attribute
Multiple Associations are allowed
Make it consistent with the formatting of the other fields in the same group (e.g occupation)
The TEI mapping is /TEI/text/body/listPerson/person/affiliation

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/c1e377f659d281a019c8f03918283f45e3ad7755

**Comment by ilovan** [comment]
confirmed
