### ISSUE TITLE
using the date picker to add a date crashes the forms

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#24]
![jul-24-2018 14-56-47](https://user-images.githubusercontent.com/6600070/43165709-d60793d2-8f51-11e8-93ce-25c8d6ee49b8.gif)

This happens on a Mac, in both Firefox and Chrome.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/a588ba575402d554c28013f27f01e4b247ce6d7d

**Comment by ilovan** [comment]
confirmed fixed
