### ISSUE TITLE
Feedback on form UI

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/cwrc-entity-management-forms-static#26]
Currently we have this look
![form more padding](https://user-images.githubusercontent.com/882444/43215302-c7420b80-9009-11e8-989b-2a4f13ec5889.png)

I can also reduce the amount of padding/grouping
![form less padding](https://user-images.githubusercontent.com/882444/43215308-cca5e074-9009-11e8-88cf-cabc8b42fe5e.png)

Preferences?
@SusanBrown @ilovan

**Comment by ilovan** [comment]
How would option 2 look like with Variant names or same as expanded?

**Comment by ajmacdonald** [comment]
![form less padding expanded](https://user-images.githubusercontent.com/882444/43218022-389a5646-9011-11e8-964d-dd81efb4a1c5.png)
@ilovan

**Comment by SusanBrown** [comment]
I think (and so did my small survey group here) that less padding looks better, so please reduce if that change would be quick to implement.

**Comment by ajmacdonald** [comment]
@SusanBrown it is. Will do.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/d398b981bd07226590f857a45e7b0cee753efab8

**Comment by ilovan** [comment]
confirmed
