### ISSUE TITLE
Improve error look when a required field is not filled in. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#29]
## Expected Behaviour

Red highlight is ok 

Empty dialog bubble is not: maybe have it say "required field"? Also, could you make it so that the check for the required fields happens only when the user tries to submit the entity? 
People may want to fill in the form asynchronously, which now causes these error messages to pop up as soon as you try to fill in a field that is below a required field ahead of the required field.

## Current Behaviour

![image](https://user-images.githubusercontent.com/6600070/43325635-716bee4e-9174-11e8-8c80-5b92a7d91d0c.png)

**Comment by ajmacdonald** [comment]
Caused by https://github.com/Semantic-Org/Semantic-UI/issues/6439

**Comment by ajmacdonald** [comment]
Temporary override is in place, until they update their repo

**Comment by ilovan** [comment]
Thanks @ajmacdonald , I confirm that the override is working.
