### ISSUE TITLE
Place within date fields has a different "remove button" than similar fields in the form.

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#34]
Should have a minus

![image](https://user-images.githubusercontent.com/6600070/43464309-062cc5b4-9498-11e8-809a-fc55fc8153c4.png)

**Comment by ajmacdonald** [comment]
1fdef5e7116d1d5e267db516e67bee1176131b09

**Comment by ilovan** [comment]
confirmed
