### ISSUE TITLE
Organization entity: change organization to org in the xPaths

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#35]
Sorry @ajmacdonald , my bad: it's `/TEI/text/body/listOrg/org` not `/TEI/text/body/listOrg/organization` in all xPaths

**Comment by ajmacdonald** [comment]
f73ae03856df58d8162b6d18c37a0e6d93e9378b

**Comment by ilovan** [comment]
confirmed
