### ISSUE TITLE
Place entity: move <idno> to be the last child of the the <place> element. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#36]
Just another TEI quirk that applies to the place entities only (and not to org or person)
In the forms, for the sake of consistency, leave the "SameAs" field where it is.

**Comment by ajmacdonald** [comment]
6a01a1970c3c3f7de6fc60e10fd44f514856c9d7

**Comment by ilovan** [comment]
confirmed
