### ISSUE TITLE
Organization: add organization type user input box 

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#39]
@ajmacdonald , change of plan:

Please add `/TEI/text/body/listOrg/org/trait/ab` with the following attributes on `trait`:

- @type="orgType" 
- @cert

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/bbd1aad105d825cd1f702316e52355e11bb575b8

**Comment by ilovan** [comment]
confirmed
