### ISSUE TITLE
Language dropdown order

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#41]
@ajmacdonald , is there a way to change the order here so that English pops up first? I foresee a lot of Old English going around, as people used with drop-downs are likely to select the first choice by default

![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/82870938-e7e5-4007-9820-c7b2070e45b0)

**Comment by ajmacdonald** [comment]
Yes that should be possible. What about having common languages at the top of the list?

**Comment by ilovan** [comment]
If that is easier than having them grouped as they are now but with the most likely at the top of the group, then let's go with that

**Comment by ajmacdonald** [comment]
There's really no concept of "group" in the resource I'm using, it's just one long list.
Which languages should be at the top?

**Comment by ilovan** [comment]
I think just plain alphabetical indexing would solve the problem, as we have now: 
<img width="565" alt="screen shot 2018-08-15 at 11 27 29 am" src="https://user-images.githubusercontent.com/6600070/44162669-37f61e00-a07e-11e8-8835-b394bdf01f58.png">

**Comment by ajmacdonald** [comment]
acd7dc503e61729f1d9f2461518f8eaf5b175693

**Comment by ilovan** [comment]
This is really weird, now you have them ordered alphabetically in the dropdown, but when one starts to type in, the Autocomplete is weird:

![image](https://user-images.githubusercontent.com/6600070/44175470-7d791200-a0a3-11e8-9e5f-00460e0bc192.png)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/acd7dc503e61729f1d9f2461518f8eaf5b175693

**Comment by ilovan** [comment]
I think the Autocomplete should favour the line items that start with string already typed over items that contain the string somewhere in their body. 
![image](https://user-images.githubusercontent.com/6600070/44176231-45bf9980-a0a6-11e8-846a-76915c66af77.png)

should have the last three at the top and the first two at the bottom.

**Comment by ilovan** [comment]
@ajmacdonald , moving this back to in-progress because I don't see it changed yet.

**Comment by ajmacdonald** [comment]
3a2cbd2154489b91d516e3309a5306f015c92d55

**Comment by ajmacdonald** [comment]
@ilovan should be fixed now

**Comment by ilovan** [comment]
confirmed on all instances
