### ISSUE TITLE
Organize Project drop-down alphabetically

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#42]
<img width="403" alt="screen shot 2018-08-15 at 10 22 59 am" src="https://user-images.githubusercontent.com/6600070/44159628-383deb80-a075-11e8-84df-fd58c3a9eeca.png">

**Comment by ajmacdonald** [comment]
8b974c5bb084b817556aeecb9ccb07d6a645ae48

**Comment by ilovan** [comment]
Confirmed
