### ISSUE TITLE
CWRC Place lookups: returned entities preview "page not found"error  because URL bad structure

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#44]
The popup attempts to display https://dev-02.cwrc.ca/islandora/object/islandora/object/cwrc:330b3ecb-328f-4147-8a73-3b2bc345dfd1 instead of https://dev-02.cwrc.ca/islandora/object/cwrc:330b3ecb-328f-4147-8a73-3b2bc345dfd1

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/a362c596ed3a808089bf70657f3c6f0158e4d08d

**Comment by ilovan** [comment]
confirmed on dev-02.cwrc.ca
