### ISSUE TITLE
Create new title entities behaviour

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#47]
## Expected Behaviour

1. In CWRC-Writer, user clicks on "Tag text/title"
2. User is unable to find the title in the lookups
3. User Clicks on "Create new" in the lookups
          **Result:** Popup, with the following text and two buttons: OK and Cancel
        Text:

    > "A new window will open, where you can navigate to the desired collection and create the new entity (a citation object). Once you're done, return to the current window and rerun the title search. The new entity you created will show up in the results and you will be able to tag it."

**Comment by ilovan** [comment]
@SusanBrown , can you please weigh in on the text?

**Comment by SusanBrown** [comment]
Very quickly, in haste, so please suggest revisions if this doesn’t seem right, and please choose between the two:

"To create a new title entity, navigate the the appropriate collection and create a new bibliographical record."

or

"To create a new title entity, navigate the the appropriate CWRC collection and create a new citation object."

On Sep 25, 2018, at 1:39 PM, Mihaela Ilovan <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/SusanBrown> , can you please weigh in on the text?

**Comment by ilovan** [comment]
@ajmacdonald , 
@SusanBrown just slacked me that she would actually prefer my version of the text, so let's go with that.

**Comment by ajmacdonald** [comment]
@ilovan how are we determining what the desired collection is? Is it the same process as for the entity management forms?

**Comment by ilovan** [comment]
Nope - the new window mentioned in the popup message should open to the CWRC top level collection https://beta.cwrc.ca/islandora/object/islandora%3Aroot
the users should be able to navigate from there to the desired collection. Once there, they would click on "Add item" and follow the steps to create a citation object.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-PublicEntityDialogs/commit/35095ee67ac2bbfd59680f65228c644c16ed3b6e

**Comment by ilovan** [comment]
confirmed
