### ISSUE TITLE
When trying to edit a non tei entity, return the user to the entity lookup, rather than move her to the next screeen, as if she had selected to tag that entity.

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#49]

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-PublicEntityDialogs/commit/58747c4745756e84b7566c7286f12f22c1747c13
https://github.com/cwrc/CWRC-PublicEntityDialogs/commit/3ae029b41b4fae1e786ffbf6e86cc48366a314be

**Comment by ilovan** [comment]
confirm on all servers
