### ISSUE TITLE
Lookup button should disappear once something has been added within that instance of the tag

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#5]
## Expected Behaviour

For example: 
Within a new instance of " Same as"  I click on "Add person", search for a person entity and select it:
I would expect that once this is done, the "Add person" button within that instance would disappear or be replaced by "Replace person", whichever is easier to code. 
If the "Add person" button disappears, I would expect that the entity name and link are flushed to the left border of the field. 

## Current Behaviour
"Add person" persists within that instance of the tag:
![image](https://user-images.githubusercontent.com/6600070/42887221-ae04da78-8a62-11e8-962c-a7a523fa9345.png)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/c6f4c93db71acdc0ab2e215175e622f1708051cd
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/66200e4bae1c558f307cbc1d9ba1f156e97ff91d

**Comment by ilovan** [comment]
confirmed
