### ISSUE TITLE
CWRC entity lookups not displaying the project logo properly

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#51]
## Expected Behaviour
Each entity returned by the lookups should be listed with its project logo

## Current Behaviour
REED entity is shown with the CWRC logo

## Possible Solution
?

## Steps to Reproduce (for bugs)

1. Go to a CWRC Document object, for example: https://dev-02.cwrc.ca/islandora/object/cwrc%3Ae08851f8-21be-40f2-9981-ff5574464d52/edit-cwrc
2. Select some text
3. Click on tag person
4. Replace text selected with "Abnett"
5. 
![image](https://user-images.githubusercontent.com/6600070/47188530-add46b00-d2f5-11e8-9510-b9cb08e95cb8.png)

"Abnett, William" is a REED entity, with a REED namespace, and based on th elogic we discussed, it should display the REED logo:

https://dev-02.cwrc.ca/islandora/object/cwrc%3A1bd7767a-afdc-4300-9ffa-31652e4d9a04

**Comment by ajmacdonald** [comment]
Currently I'm using the entity's PID to determine the project. In this case the PID has a cwrc namespace. Given the available data https://dev-02.cwrc.ca/islandora/cwrc_entities/v1/search/person?query=abnett&limit=100&page=0 what is the preferred method for determining an entity's project?

**Comment by ilovan** [comment]
@ajmacdonald , this has been dealt with already and is no longer an issue.
