### ISSUE TITLE
Authenticated user can see REED collections in the collection dropdown, even when they don't have a REED user role.

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#52]
[when creating a new entity from within CWRC_Writer]

## Expected Behaviour
User should only see the CWRC entity collection corresponding to that entity type.
## Current Behaviour
User can see the REED colelction as well in the dropdown, though they don't have management privileges to that collection.

**Comment by ilovan** [comment]
@bradklaver , @ajmacdonald  - I am not sure in whose court this is supposed to be - so I'm tagging you both. Looks like a Drupal /XACML permission issue to me.

**Comment by bradklaver** [comment]
Fixed this on dev-02.  @ilovan

**Comment by ilovan** [comment]
Now he sees Orlando and CWRC in the dropdown.
Also, if he selects Orlando, he is actually able to add an entity to that collection. He added this one: https://dev-02.cwrc.ca/islandora/object/orlando:7afd952f-bef6-4cba-bec9-1eabe22f5e8e/manage/datastreams

**Comment by bradklaver** [comment]
Hi Mihaela, I think what you have described is desired.  Let me know if that's not the case.

**Comment by ilovan** [comment]
No, he should not see "Orlando People" as an option in the collection picker drop-down, let alone be able to save an entity in that collection, as he is not included in the list of people/roles that are allowed to manage that collection.
See https://dev-02.cwrc.ca/islandora/object/orlando%3ApersonEntityCollection/manage/xacml

**Comment by bradklaver** [comment]
@ilovan I foudn that my access call was looking at View permissions, I've switched them to Manage, however, now Brandon can't see any collections, because he's just authenticated and belongs to no groups. This is what he'll see until he can modify any of the entity collections

![2018-10-26_10-47-29](https://user-images.githubusercontent.com/210245/47573989-9b1cf000-d90c-11e8-9750-d934da2a9521.gif)

**Comment by bradklaver** [comment]
@ajmacdonald Might want to provide some extra handling for the case wher ethey don't have write/manage access to any collections

**Comment by ilovan** [comment]
specific issue created at https://github.com/cwrc/cwrc-entity-management-forms-static/issues/59.
will close current one
