### ISSUE TITLE
Entity locking doesn't seem to be working

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#53]
## Steps to Reproduce (for bugs)

1.Open Phil Harmonica (test) in the editing form from the CWRC_Writer entity lookup
2.Under a different user, go to https://dev-02.cwrc.ca/islandora/object/cwrc:4d6afd04-b4fd-4cd6-8ab4-09d8048b4d7e and Click on edit
Result: The forms populate in both these instances.

##Expected result
A warning message that the 
entity can`t be locked at the time.

## Your Environment
* URL: dev-02.cwrc.ca

**Comment by bradklaver** [comment]
@ajmacdonald  
![image](https://user-images.githubusercontent.com/210245/47642857-27632900-db40-11e8-9353-6286dd6fa390.png)
I think the lock status request is returning the right information.  Can you look at this?

**Comment by ajmacdonald** [comment]
I don't have time to deploy right now, but this should fix the issue: https://github.com/cwrc/cwrc-entity-management-forms-static/commit/2c17961b75bdb25b74679f160ce314c6fdb36b88

**Comment by bradklaver** [comment]
Awesome
