### ISSUE TITLE
test-01: project drop-down not working on variant names, project-specific names

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#56]
@ajmacdonald , I am assuming the re is some code that would create the json you are using to populate the dropdown on dev-02. Can you please point @bradklaver to where that is located or show him the resulting call?

**Comment by bradklaver** [comment]
@ilovan Can you describe what is intended to be done here a little more?

**Comment by ajmacdonald** [comment]
@ilovan yes, need more detail for this issue
