### ISSUE TITLE
CWRC production: Entity forms fail to submit new entities

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#57]
Error messages in Firefox:
![image](https://user-images.githubusercontent.com/6600070/53890494-8f8db400-3fe5-11e9-99fb-d5e9c1a537ac.png)

Error messages in Chrome incognito (more informative I think):
![image](https://user-images.githubusercontent.com/6600070/53890420-6e2cc800-3fe5-11e9-8a22-d8a627ccf69e.png)

**Comment by ajmacdonald** [comment]
It looks like the issue is being caused by the beta.cwrc.ca URL re-directing to cwrc.ca. The [host parameter](https://github.com/cwrc/cwrc-entity-management-forms-static/blob/master/.env#L1) is probably set to beta.cwrc.ca and should be changed to cwrc.ca.

**Comment by ilovan** [comment]
@ajmacdonald , at 
https://github.com/cwrc/cwrc-entity-management-forms-static/blob/master/.env#L1 the host parameter is set to dev-02, not beta - just saying

**Comment by ajmacdonald** [comment]
Those values are examples. The file needs to be customized before being deployed on the server.

**Comment by ajmacdonald** [comment]
Note to self: replace with `window.location.origin`
