### ISSUE TITLE
Tighten up the lookup enabled fields

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#6]
## Expected Behaviour
Certainty dropdown should be on the same row as the "Add____" button.
Once an entity has been selected, certainty should still be on the same row as the selected entity (and potentially the "Replace entity" button (see #5 )

## Current Behaviour

![image](https://user-images.githubusercontent.com/6600070/42887872-31e15546-8a64-11e8-906a-96a610d497b3.png)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/eb76fbacbd36091c1127c287ea3b1ac429918254

**Comment by ilovan** [comment]
confirmed
