### ISSUE TITLE
Trying to edit entities that are locked by someone else requires better response

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#60]
## Expected Behaviour
Message: "The entity [name](URL) you are attempting to edit is being locked by someone else"

## Current Behaviour
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/2a77a8ee-bde6-4e6b-8797-bb37e72bd3fb)

**Comment by ajmacdonald** [comment]
There is already an error message in place to indicate if the entity is locked. You're getting this message for a different reason.

**Comment by ilovan** [comment]
Locked entity : https://dev-02.cwrc.ca/islandora/object/cwrc%3A12c1fbdc-21fc-45c5-acb2-009723a6676d (locked by CWRCTestEditor)
Try editing it from within CWRC-Writer entity lookup from another user
Result:
![image](https://user-images.githubusercontent.com/6600070/62732785-71880d80-b9e2-11e9-9890-050f28e62fc3.png)

So, bottom line, I think you are right - I am not sure why I was getting that result and I can't reproduce it now with a TEI entity. Will close for now.
