### ISSUE TITLE
Unable to save entities bc of hardcoded dev-02 API endpoint

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#64]
When hitting "Submit" on the entity management forms, we get the following console error:

![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/169eb6ab-6f6e-4366-a6fc-b938c0704ca8)

**Comment by ilovan** [comment]
OK - so the collections options is a deployment issue on the production Drupal side. 
the saving issue is an entity forms code issue and could be a hard coded reference to the dev-01 server (see screenshot above). Note that I am modifying the title of the issue and the description to reflect this find

**Comment by lucaju** [comment]
Yup. You are right. The rest API is hardcoded pointing to `dev-02`. 
<img width="1036" alt="Screen Shot 2020-09-24 at 1 50 09 PM" src="https://user-images.githubusercontent.com/1254739/94181191-137beb00-fe6d-11ea-8ed3-9a75aff54a5f.png">

This is specific to `cwrc-management-forms-static` repo. Can you move this issue to the right repository?

**Comment by ilovan** [comment]
There is no `cwrc-management-forms-static`.
Just a `cwrc-entity-management-forms-static` and this ticket is in it.

**Comment by lucaju** [comment]
Sorry. my mistake Zenhub confused me. :p

**Comment by ilovan** [comment]
FYI @lucaju 
title and description updated

**Comment by lucaju** [comment]
Done: bc17849adb462b075cee1cb0c89c38277b9435cd
But we must test on dev-02 or test-01 to check if this solves the issue.
