### ISSUE TITLE
Gender should also have the certainty attribute

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc-entity-management-forms-static#7]
Gender should have the certainty attribute, just like all other tags in the Properties field-set.

TEI mapping: /TEI/text/body/listPerson/person/sex/@cert

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-entity-management-forms-static/commit/b530029f1e0f289af067cfb35c9ba424ae0e8384

**Comment by ilovan** [comment]
confirmed
